# Generated by Django 3.2.4 on 2021-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210713_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='awards',
            field=models.ManyToManyField(to='main_app.Award'),
        ),
    ]
